services:
  mysql:
    image: mysql:8.0
    container_name: inspection_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inspection_app
      MYSQL_USER: inspection_user
      MYSQL_PASSWORD: inspection_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - inspection_network
    command: --default-authentication-plugin=mysql_native_password

  carbone1:
    image: carbone/carbone-ee:full
    container_name: inspection_carbone_1
    restart: unless-stopped
    ports:
      - '3001:4000'
    environment:
      - NODE_ENV=production
      - CARBONE_EE_STUDIO=true
    networks:
      - inspection_network
    volumes:
      - carbone_data_1:/tmp

  # app:
  #   build: .
  #   container_name: inspection_app
  #   restart: unless-stopped
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_NAME=inspection_app
  #     - DB_USER=inspection_user
  #     - DB_PASSWORD=inspection_password
  #   depends_on:
  #     - mysql
  #   networks:
  #     - inspection_network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

volumes:
  mysql_data:
  carbone_data_1:
  carbone_data_2:
  carbone_data_3:

networks:
  inspection_network:
    driver: bridge
